trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 9.1.10
      DBCVERNODOTS: 9110
