trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 6.5.1
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 6.4.1
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 6.3.1
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 6.2.0
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 6.1.0