# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    variables:
      DBCVER: 6.4.1
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          command: login

      - task: Docker@2
        displayName: Build
        inputs:
          command: build
          containerRegistry: 'DockerHub'
          repository: datathirstltd/dbconnect
          tags: |
            $(Build.BuildId)
            latest
            $(DBCVER)
          arguments: --build-arg DBCVER=$(DBCVER)

      - task: Docker@2
        displayName: Push
        inputs:
          command: push
          containerRegistry: 'DockerHub'
          repository: datathirstltd/dbconnect
          tags: |
            $(Build.BuildId)
            latest
            $(DBCVER)


  - job: Build1
    displayName: Build
    variables:
      DBCVER: 6.5.1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          command: login

      - task: Docker@2
        displayName: Build
        inputs:
          command: build
          containerRegistry: 'DockerHub'
          repository: datathirstltd/dbconnect
          tags: |
            $(Build.BuildId)
            latest
            $(DBCVER)
          arguments: --build-arg DBCVER=$(DBCVER)

      - task: Docker@2
        displayName: Push
        inputs:
          command: push
          containerRegistry: 'DockerHub'
          repository: datathirstltd/dbconnect
          tags: |
            $(Build.BuildId)
            latest
            $(DBCVER)  