# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - template: .builds/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 641