trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - template: .build/azure-pipelines-job-build.yml
    parameters:
      DBCVER: 7.3.4b
      DBCVERNODOTS: 734b
