# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build
        inputs:
          command: build
          containerRegistry: 'DockerHub'
          repository: dbconnect
          tags: |
            $(Build.BuildId)
            beta
            $(DBCVER)
          arguments: --DBCVER=$(DBCVER)

      - task: Docker@2
        displayName: Push
        inputs:
          command: push
          containerRegistry: 'DockerHub'
          repository: dbconnect
          tags: |
            $(Build.BuildId)
            beta
            $(DBCVER)